
services:
  app:
    build: .
    container_name: gripup
    restart: unless-stopped
    ports:
      - 8100:80
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      SERVER_NAME: ":80"
      PHP_CS_FIXER_IGNORE_ENV: 1
      DATABASE_URL: postgresql://app:${POSTGRES_PASSWORD:-password}@database/app
    volumes:
      - ./public/uploads:/app/public/uploads
    networks:
      - network_gripup

###> doctrine/doctrine-bundle ###
  database:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###
    networks:
      - network_gripup

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
networks:
  network_gripup: